Repository rasterio/rasterio, pull requests merged in 2018-12, with the labels that each got.

#1571 Exploit VRT complex source scale ratio 0 optimization
  CHANGES.txt
  rasterio/_io.pyx
  rasterio/vrt.py
  tests/test_vrt.py
Labels: bug

#1573 Turn on exceptions and use Py_ssize_t for index arrays
  CHANGES.txt
  rasterio/_io.pxd
  rasterio/_io.pyx
  rasterio/_shim.pxd
  rasterio/_shim1.pyx
  rasterio/_shim20.pyx
  rasterio/shim_rasterioex.pxi
  tests/test_warp.py
Labels: bug, cython

#1579 Fix "ValueError: Buffer dtype mismatch" on win_amd64
  rasterio/_io.pyx
Labels: Windows, bug

#1583 Reduce log level when logging colormaps
  rasterio/_base.pyx
Labels: bug

#1591 Add anonymous Env in DatasetBase.__enter__ if needed
  CHANGES.txt
  rasterio/_base.pxd
  rasterio/_base.pyx
  rasterio/io.py
  rasterio/vrt.py
Labels: bug
