Repository rasterio/rasterio, pull requests merged in 2022-11, with the labels that each got.

#2634 BUG: ensure default driver for tif to be GTiff
  rasterio/_base.pyx
Labels: bug

#2629 BUG: fix get_data_window for nodata=nan, fixes #2628
  rasterio/windows.py
  tests/test_windows.py
Labels: bug

#2626 Fix possible init crash when Windows PATH has empty entry
  rasterio/__init__.py
Labels: bug

#2619 TST: Don't use fixed port for test server
  tests/test_warp.py
Labels: testing

#2640 Backport to maint-1.3
  rasterio/__init__.py
  rasterio/windows.py
  tests/test_warp.py
  tests/test_windows.py
Labels: backport-1.3

#2584 DOC: Fixed (row, col) to (col, row) in Dataset Georeferencing section
  docs/quickstart.rst
Labels: documentation

#2637 pull AZURE_STORAGE_ACCESS_KEY from env if not provided as arg to AzureSession
  rasterio/session.py
  tests/test_session.py
Labels: bug

#2643 BUG: pull AZURE_STORAGE_ACCESS_KEY from env if not provided as arg (#2637)
  rasterio/session.py
  tests/test_session.py
Labels: backport-1.3

#2650 CI: Update latest build to build git & remove GML
  .github/workflows/test_gdal_latest.yaml
  ci/gdal-compile.sh
  tests/test__env.py
Labels: ci

#2652 Avoid narrowing file stream position to `int` inside `filepath_tell`
  rasterio/_filepath.pyx
  rasterio/gdal.pxi
Labels: bug, cython

#2647 TST: Update S3 paths
  tests/conftest.py
  tests/test_env.py
  tests/test_rio_info.py
  tests/test_warpedvrt.py
Labels: testing
