Repository rasterio/rasterio, pull requests merged in 2022-04, with the labels that each got.

#2335 Merge _crs with crs
  Dockerfile
  Makefile
  docs/Makefile
  docs/index.rst
  rasterio/_crs.pyx
  rasterio/crs.pxd
  rasterio/crs.py
  rasterio/crs.pyx
  requirements-dev.txt
  setup.py
  tests/test__crs.py
  tests/test_crs.py
Labels: refactor

#2423 Rename rasterio.path to rasterio._path
  CHANGES.txt
  Makefile
  rasterio/__init__.py
  rasterio/_base.pyx
  rasterio/_io.pyx
  rasterio/_path.py
  rasterio/io.py
  rasterio/path.py
  rasterio/rio/options.py
  rasterio/session.py
  rasterio/shutil.pyx
  rasterio/vrt.py
  tests/test_path.py
Labels: bug

#2419 fix RPC metadata parsing
  rasterio/rpc.py
Labels: bug

#2422 Fix ignored z values when using transform mixin methods with rpcs
  rasterio/transform.py
  tests/test_transform.py
Labels: bug

#2430 Fix rpcs parsing
  rasterio/rpc.py
Labels: bug

#2237 ENH: Add CRS.units_factor to return units for both projected and geographic CRS
  rasterio/crs.pyx
  rasterio/gdal.pxi
  tests/test_crs.py
Labels: enhancement

#2393 BUG: Prevent core dump with invalid input to rasterize
  rasterio/_features.pyx
  tests/test_features.py
Labels: bug

#2432 No more epsilon usage in transform.rowcol and window.from_bounds
  CHANGES.txt
  Makefile
  rasterio/merge.py
  rasterio/rio/merge.py
  rasterio/transform.py
  rasterio/windows.py
  tests/test_rio_merge.py
Labels: bug

#2434 Produce slices that don't erronously select from an array
  CHANGES.txt
  Dockerfile
  Makefile
  rasterio/windows.py
  tests/test_windows.py
Labels: bug

#2316 Update property declarations.
  rasterio/_base.pyx
Labels: refactor

#2438 Pass --wo and --to options through to the warper and transformer
  CHANGES.txt
  rasterio/rio/warp.py
  tests/test_rio_warp.py
Labels: enhancement

#2441 Add method for getting raster band stats
  CHANGES.txt
  rasterio/_base.pyx
  rasterio/_io.pyx
  rasterio/gdal.pxi
  rasterio/rio/info.py
  tests/test_dataset.py
  tests/test_rio_info.py
Labels: enhancement

#2450 BUG: Fix output file dtype in merge
  rasterio/merge.py
  rasterio/rio/merge.py
  tests/test_rio_merge.py
Labels: bug
