Repository rasterio/rasterio, pull requests merged in 2022-09, with the labels that each got.

#2583 Create destfile with proper dictionary
  examples/thread_pool_executor.py
Labels: bug, documentation

#2581 ENH: Add support for writing GeometryCollection
  rasterio/_features.pxd
  rasterio/_features.pyx
  tests/test_warp.py
Labels: enhancement

#2594 Remove _loading, copy it into __init__
  .gitignore
  CHANGES.txt
  rasterio/__init__.py
  rasterio/_loading.py
  rasterio/drivers.py
  rasterio/env.py
  rasterio/features.py
  rasterio/fill.py
  rasterio/io.py
  rasterio/mask.py
  rasterio/merge.py
  rasterio/plot.py
  rasterio/sample.py
  rasterio/session.py
  rasterio/tools.py
  rasterio/transform.py
  rasterio/vrt.py
  rasterio/warp.py
  rasterio/windows.py
  tests/test__env.py
Labels: bug

#2577 DOC: Add a comment on dtype = int8
  docs/topics/features.rst
Labels: documentation
