Repository rasterio/rasterio, pull requests merged in 2022-12, with the labels that each got.

#2666 fix #2665: Update documentation on rasterio.features.rasterize
  rasterio/features.py
Labels: documentation

#2669 Fixes for unsigned access to S3
  rasterio/session.py
  tests/test_session.py
Labels: bug

#2687 BUG: ignore blockysize when converting untiled to tiled (#2678)
  CHANGES.txt
  rasterio/_io.pyx
  tests/test_profile.py
Labels: backport-1.3

#2688 BUG: Fixes for unsigned access to S3 (#2669)
  CHANGES.txt
  rasterio/session.py
  tests/test_session.py
Labels: backport-1.3

#2689 Handle and silence sigpipe errors
  CHANGES.txt
  rasterio/rio/blocks.py
  rasterio/rio/bounds.py
  rasterio/rio/gcps.py
  rasterio/rio/sample.py
  rasterio/rio/shapes.py
  rasterio/rio/transform.py
Labels: bug

#2686 TST: Use GDALVersion in test_gdal_version
  tests/test_rio_main.py
Labels: testing
