Repository rasterio/rasterio, pull requests merged in 2022-08, with the labels that each got.

#2536 BUG: RasterioDeprecationWarning import missing
  rasterio/__init__.py
Labels: bug

#2537 DOC: Improve links & add Band to docs
  docs/api/rasterio.rst
  docs/quickstart.rst
  docs/topics/color.rst
  docs/topics/concurrency.rst
  docs/topics/configuration.rst
  docs/topics/datasets.rst
  docs/topics/features.rst
  docs/topics/fillnodata.rst
  docs/topics/georeferencing.rst
  docs/topics/image_options.rst
  docs/topics/masking-by-shapefile.rst
  docs/topics/masks.rst
  docs/topics/memory-files.rst
  docs/topics/overviews.rst
  docs/topics/profiles.rst
  docs/topics/reading.rst
  docs/topics/reproject.rst
  docs/topics/resampling.rst
  docs/topics/switch.rst
  docs/topics/tags.rst
  docs/topics/transforms.rst
  docs/topics/virtual-warping.rst
  docs/topics/windowed-rw.rst
  docs/topics/writing.rst
  rasterio/__init__.py
Labels: documentation

#2548 Silence non-informative errors from _delete_dataset_if_exists
  CHANGES.txt
  rasterio/_base.pyx
  rasterio/_io.pyx
  tests/test_write.py
Labels: bug

#2538 Fix broadcasting of coords in `rasterio.transform.xy`
  rasterio/transform.py
  tests/test_transform.py
Labels: enhancement

#2510 get_data_window cleanup
  rasterio/windows.py
  tests/test_windows.py
Labels: bug, refactor

#2560 Fix broadcasting of coords in `rasterio.transform.xy` (#2538)
  rasterio/transform.py
  tests/test_transform.py
Labels: backport-1.3

#2559 get_data_window cleanup (#2510)
  rasterio/windows.py
  tests/test_windows.py
Labels: backport-1.3

#2556 BUG: RasterioDeprecationWarning import missing (#2536)
  rasterio/__init__.py
Labels: backport-1.3

#2557 ENH: Add support for PROJ_DATA environment variable (#2530)
  .travis.yml
  docs/faq.rst
  rasterio/_env.pyx
  rasterio/env.py
  rasterio/rio/env.py
  setup.py
  tests/test_crs.py
Labels: backport-1.3

#2558 Pass along strides to GDAL in MemoryDataset #2511 (#2512)
  rasterio/_io.pyx
  tests/test_features.py
  tests/test_warp.py
Labels: backport-1.3

#2569 Add missing warnings import in transform.py
  rasterio/transform.py
Labels: bug

#2574 DOC: Use sphinx-click for CLI documentation
  README.rst
  docs/api/rasterio.rio.blocks.rst
  docs/api/rasterio.rio.bounds.rst
  docs/api/rasterio.rio.calc.rst
  docs/api/rasterio.rio.clip.rst
  docs/api/rasterio.rio.convert.rst
  docs/api/rasterio.rio.edit_info.rst
  docs/api/rasterio.rio.env.rst
  docs/api/rasterio.rio.gcps.rst
  docs/api/rasterio.rio.helpers.rst
  docs/api/rasterio.rio.info.rst
  docs/api/rasterio.rio.insp.rst
  docs/api/rasterio.rio.main.rst
  docs/api/rasterio.rio.mask.rst
  docs/api/rasterio.rio.merge.rst
  docs/api/rasterio.rio.options.rst
  docs/api/rasterio.rio.overview.rst
  docs/api/rasterio.rio.rasterize.rst
  docs/api/rasterio.rio.rm.rst
  docs/api/rasterio.rio.rst
  docs/api/rasterio.rio.sample.rst
  docs/api/rasterio.rio.shapes.rst
  docs/api/rasterio.rio.stack.rst
  docs/api/rasterio.rio.transform.rst
  docs/api/rasterio.rio.warp.rst
  docs/api/rasterio.rst
  docs/conf.py
  rasterio/rio/blocks.py
  requirements-dev.txt
  setup.py
Labels: documentation
