Repository rasterio/rasterio, pull requests merged in 2023-04, with the labels that each got.

#2803 CI: Use ghcr.io/osgeo/gdal docker image
  .github/workflows/test_gdal_latest.yaml
  .github/workflows/tests.yaml
  Dockerfile
Labels: ci

#2804 TST: Update test_transform_bounds_densify to match GDAL
  tests/test_warp.py
Labels: testing

#2788 CI: test with GDAL 3.6.3 & PROJ 9.2.0
  .github/workflows/test_gdal_latest.yaml
  .github/workflows/tests.yaml
Labels: ci

#2790 BUG: Fix calculation of bounds in transform.array_bounds
  rasterio/transform.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_transform.py
Labels: bug

#2813 Fix for issue #2582
  docs/quickstart.rst
Labels: documentation
