Repository rasterio/rasterio, pull requests merged in 2023-12, with the labels that each got.

#2980 Deallocate warp_extras at end of _reproject()
  CHANGES.txt
  rasterio/_warp.pyx
Labels: bug, cython, warp

#2864 Allow (float) windowed reads smaller than 1.0 to handle extreme zoom use case
  rasterio/_io.pyx
Labels: bug

#2869 Close derived datasets automatically when MemoryFile is closed
  rasterio/io.py
  tests/test_memoryfile.py
Labels: bug

#2985 Test against release/3.8
  .github/workflows/test_gdal_latest.yaml
Labels: testing, ci

#2870 Prevent interpreter segfaults with closed MemoryFile.
  rasterio/_io.pyx
  tests/test_memoryfile.py
Labels: bug

#2989 Operations on closed MemoryFile and ZipMemoryFile raise ValueError
  CHANGES.txt
  rasterio/_io.pyx
  rasterio/io.py
  tests/test_memoryfile.py
Labels: bug

#2936 Implemented bulk affine transformations with numpy
  rasterio/transform.py
Labels: refactor

#2702 Allow crop and invert in raster_geometry_mask
  rasterio/mask.py
  tests/test_mask.py
Labels: enhancement

#2884 Add src_geoloc_array kwarg to reproject and _reproject
  Makefile
  rasterio/_warp.pyx
  rasterio/warp.py
  tests/test_warp.py
Labels: enhancement, warp

#2909 Allow fsspec OpenFile instances as dataset name
  rasterio/__init__.py
  tests/test_pyopener.py
Labels: enhancement

#2873 Add hist_range arg to rasterio.plot.show_hist
  rasterio/plot.py
  tests/test_plot.py
Labels: enhancement, plotting

#3001 Change hist_range arg to range
  CHANGES.txt
  rasterio/plot.py
  tests/test_plot.py
Labels: enhancement, plotting

#2956 Vendor snuggs
  CHANGES.txt
  rasterio/_show_versions.py
  rasterio/_vendor/snuggs.py
  rasterio/rio/calc.py
  setup.py
  tests/test_show_versions.py
Labels: packaging, dependencies
