Repository rasterio/rasterio, pull requests merged in 2023-02, with the labels that each got.

#2744 Additional info for offset parameter in transform.xy
  rasterio/transform.py
Labels: documentation

#2760 Add a new StatisticsError exception class
  CHANGES.txt
  rasterio/_base.pyx
  rasterio/_io.pyx
  rasterio/errors.py
  rasterio/transform.py
  tests/data/all-nodata.tif
  tests/test_dataset.py
  tests/test_statistics.py
Labels: bug

#2761 Dodge empty sequences when computing bounds.
  CHANGES.txt
  rasterio/_features.pyx
Labels: bug

#2740 Raise exception when CRS differs during merge
  rasterio/merge.py
  tests/test_merge.py
Labels: bug, enhancement
