Repository rasterio/rasterio, pull requests merged in 2023-05, with the labels that each got.

#2821 Windows Binaries are now on the official pypi channel
  README.rst
Labels: documentation

#2832 Fix the nodata mask value in sample_gen()
  rasterio/sample.py
  tests/conftest.py
  tests/test_sampling.py
Labels: bug

#2833 CI: Add GDAL 3.7 to the test matrix
  .github/workflows/tests.yaml
Labels: ci

#2814 DOC: Clarify required params of rasterio.warp.calculate_default_transform in docstring
  rasterio/warp.py
Labels: documentation

#2835 Add rio-blocks documentation
  CHANGES.txt
  docs/cli.rst
  rasterio/rio/blocks.py
Labels: documentation

#2837 Allow color values greater than 256 in colormaps
  CHANGES.txt
  rasterio/_io.pyx
Labels: bug

#2795 DOC: improve doc for window.round_lengths and round_offsets
  rasterio/windows.py
Labels: documentation
