Repository rasterio/rasterio, pull requests merged in 2023-01, with the labels that each got.

#2708 installation.rst - Update GDAL minimum version 1.11 -> 3.1 as of #2448
  docs/installation.rst
Labels: documentation

#2709 installation.rst - update notes for Windows installation
  docs/installation.rst
Labels: documentation

#2704 Fix numpy deprecation warning
  tests/test_gdal_raster_io.py
  tests/test_rio_merge.py
Labels: testing

#2707 Update write_mask to accept Numpy booleans, to enable writing optimized masked array (mask == mp.ma.nomask)
  rasterio/_io.pyx
  tests/test_write.py
Labels: bug

#2716 PERF: Minor performance improvements to dtypes
  rasterio/dtypes.py
Labels: enhancement

#2732 BUG: Update write_mask to accept numpy booleans (#2707)
  rasterio/_io.pyx
  tests/test_write.py
Labels: backport-1.3

#2737 Fix ImportError with unreachable http_proxy.
  tests/conftest.py
Labels: testing
