Repository rasterio/rasterio, pull requests merged in 2023-03, with the labels that each got.

#2778 MNT: Update warp tests for GDAL 3.6 & Update GDAL versions in test matrix
  .github/workflows/tests.yaml
  tests/test_warp.py
Labels: backport-1.3

#2779 DEP: GDAL 3.3+, numpy 1.21+, Python 3.9+
  .github/workflows/tests.yaml
  .travis.yml
  Dockerfile
  Makefile
  README.rst
  docs/installation.rst
  environment.yml
  requirements.txt
  setup.py
  tests/conftest.py
  tests/test__env.py
  tests/test_boundless_read.py
  tests/test_read_boundless.py
  tests/test_rio_info.py
  tests/test_warp.py
Labels: dependencies

#2612 add python 3.11 in CI
  .github/workflows/tests.yaml
Labels: blocked

#2780 ENH: Added int8 dtype to rasterize
  rasterio/features.py
  tests/test_features.py
Labels: enhancement

#2794 DOC: Add note about PROJ_DEBUG in debug error documentation
  docs/topics/errors.rst
Labels: documentation

#2723 ENH: Added option to change merge strategy in CLI
  rasterio/rio/merge.py
  tests/test_rio_merge.py
Labels: enhancement

#2793 DOC: Consolidate intallation instructions
  README.rst
  docs/installation.rst
Labels: documentation
