Repository rasterio/rasterio, pull requests merged in 2023-06, with the labels that each got.

#2851 io_multi_band(): workaround GDAL [3.6.0,3.7.0] bug with reading band-…
  rasterio/_io.pyx
  tests/test_read.py
Labels: bug, upstream

#2859 Prevent a crash when accessing block shapes of an HDF5 file
  CHANGES.txt
  rasterio/_base.pyx
  tests/data/two-subs.h5
  tests/test_subdatasets.py
Labels: bug, cython

#2856 Improve compatibility of FilePath with GDAL's VSI system
  CHANGES.txt
  rasterio/__init__.py
  rasterio/_filepath.pyx
  rasterio/_io.pyx
  requirements.txt
  tests/test_filepath.py
Labels: bug
