Repository rasterio/rasterio, pull requests merged in 2024-08, with the labels that each got.

#3127 Add an admonition about fork to the concurrency doc
  docs/topics/concurrency.rst
Labels: documentation, concurrency

#3098 Clip rasters in chunks
  rasterio/rio/clip.py
  tests/test_rio_clip.py
Labels: enhancement

#3126 Add a new MergeError and use it in the merge tool
  rasterio/errors.py
  rasterio/merge.py
  tests/test_merge.py
Labels: bug, enhancement

#3099 Return numpy arrays from transformations
  rasterio/transform.py
  tests/test_transform.py
Labels: enhancement

#3125 ENH: enable support for extra dtypes in features.shapes: int8 and float64
  CHANGES.txt
  rasterio/_features.pyx
  rasterio/features.py
  tests/conftest.py
  tests/test_features.py
Labels: enhancement

#3131 Allow rasterize() output to be captured in datasets
  CHANGES.txt
  rasterio/_features.pyx
  rasterio/features.py
  tests/test_features.py
Labels: enhancement

#3132 Update code to Python 3.9 usage
  rasterio/__init__.py
  rasterio/_path.py
  rasterio/control.py
  rasterio/dtypes.py
  rasterio/env.py
  rasterio/features.py
  rasterio/io.py
  rasterio/merge.py
  rasterio/rio/blocks.py
  rasterio/rio/calc.py
  rasterio/rio/env.py
  rasterio/rio/gcps.py
  rasterio/rio/helpers.py
  rasterio/rio/info.py
  rasterio/rio/insp.py
  rasterio/rio/main.py
  rasterio/rio/options.py
  rasterio/rio/overview.py
  rasterio/rio/shapes.py
  rasterio/rio/warp.py
  rasterio/transform.py
  rasterio/warp.py
  tests/conftest.py
  tests/rangehttpserver.py
  tests/test__env.py
  tests/test_complex_dtypes.py
  tests/test_creation_options.py
  tests/test_crs.py
  tests/test_dataset_rw.py
  tests/test_env.py
  tests/test_filepath.py
  tests/test_gdal_raster_io.py
  tests/test_memoryfile.py
  tests/test_pad.py
  tests/test_rio_convert.py
  tests/test_rio_create.py
  tests/test_rio_options.py
  tests/test_rio_shapes.py
  tests/test_rio_warp.py
  tests/test_shutil.py
  tests/test_tag_item.py
  tests/test_tag_ns.py
  tests/test_tags.py
  tests/test_warp.py
  tests/test_warpedvrt.py
  tests/test_windows_mixins.py
  tests/test_write.py
Labels: enhancement

#3134 Add stats(), clear_stats(), update_stats(), deprecate statistics()
  CHANGES.txt
  rasterio/__init__.py
  rasterio/_io.pyx
  rasterio/gdal.pxi
  rasterio/rio/info.py
  tests/data/RGB.byte.tif.aux.xml
  tests/test_rio_info.py
  tests/test_statistics.py
Labels: enhancement

#3137 1.4b1 release
  CHANGES.txt
  rasterio/__init__.py
Labels: release

#3136 Properly set color interpretation after writing a colormap
  CHANGES.txt
  rasterio/_io.pyx
  tests/test_colormap.py
Labels: bug

#3140 Free string lists in get/set_proj_data_search_path()
  CHANGES.txt
  rasterio/_env.pyx
Labels: bug

#3145 Handle case where a MemoryFile is passed into `open`
  rasterio/__init__.py
  tests/conftest.py
  tests/data/N10W110.hgt.zip
  tests/test_memoryfile.py
Labels: bug

#3147 Document use of rasterio.band() shortcut
  docs/topics/features.rst
  rasterio/__init__.py
Labels: documentation

#3146 Never pass key if/else without returning
  CHANGES.txt
  rasterio/__init__.py
Labels: bug

#3151 _OverviewResampling is OverviewResampling
  CHANGES.txt
  rasterio/enums.py
  rasterio/rio/overview.py
  tests/test_enums.py
  tests/test_overviews.py
Labels: enhancement

#3157 Use gdalvrt.xsd as a marker for GDAL's data directory
  CHANGES.txt
  rasterio/_env.pyx
  rasterio/env.py
  tests/test__env.py
  tests/test_data_paths.py
  tests/test_env.py
Labels: bug, packaging

#3156 Use mask as alpha when reprojecting a masked array
  CHANGES.txt
  rasterio/_io.pxd
  rasterio/_warp.pyx
  rasterio/warp.py
  tests/test_warp.py
Labels: bug, enhancement, warp
