Repository rasterio/rasterio, pull requests merged in 2024-12, with the labels that each got.

#3268 Fix erroneous masking of 0-valued data
  CHANGES.txt
  rasterio/_io.pyx
  tests/test_boundless_read.py
Labels: bug

#3269 Release 1.4.3
  CHANGES.txt
  rasterio/__init__.py
Labels: release

#3270 Merge 1.4.3
  CHANGES.txt
  rasterio/__init__.py
  rasterio/_base.pyx
  rasterio/_env.pxd
  rasterio/_env.pyx
  rasterio/_fill.pyx
  rasterio/_io.pyx
  rasterio/crs.pyx
  rasterio/enums.py
  rasterio/fill.py
  rasterio/merge.py
  rasterio/windows.py
  tests/test_boundless_read.py
  tests/test_crs.py
  tests/test_env.py
  tests/test_merge.py
  tests/test_open.py
  tests/test_rio_merge.py
  tests/test_write.py
Labels: release

#3272 Force uint8 dtype for geometry mask
  rasterio/features.py
Labels: bug

#3273 Lift ndim check out of loop in GeomBuilder
  rasterio/_features.pyx
Labels: performance

#3276 Introducing cache.invalidate() and invalidate_all()
  CHANGES.txt
  rasterio/_base.pyx
  rasterio/cache.pyx
  rasterio/gdal.pxi
  setup.py
  tests/test_cache.py
Labels: enhancement, caching
