Repository rasterio/rasterio, pull requests merged in 2024-09, with the labels that each got.

#3164 CI: Use micromamba for tests
  .github/workflows/tests.yaml
Labels: ci

#3163 Release 1.3.11
  CHANGES.txt
  Dockerfile
  pyproject.toml
  rasterio/__init__.py
  rasterio/_env.pyx
  rasterio/_io.pyx
  rasterio/_warp.pyx
  rasterio/env.py
  rasterio/merge.py
  tests/test__env.py
  tests/test_colormap.py
  tests/test_data_paths.py
  tests/test_env.py
  tests/test_mask_creation.py
  tests/test_merge.py
  tests/test_rio_merge.py
  tests/test_update.py
Labels: packaging, release

#3158 docs: :memo: clarify usage of rpc_height in RPCTransformer usage example
  docs/topics/transforms.rst
Labels: documentation

#3159 This is 1.4b2
  CHANGES.txt
  rasterio/__init__.py
  setup.py
Labels: release

#3166 DEP: GDAL 3.5+, numpy 1.24+
  .github/workflows/tests.yaml
  docs/installation.rst
  rasterio/_filepath.pyx
  rasterio/_io.pyx
  rasterio/_warp.pyx
  rasterio/dtypes.py
  rasterio/features.py
  requirements.txt
  setup.py
  tests/conftest.py
  tests/test__env.py
  tests/test_dtypes.py
  tests/test_err.py
  tests/test_features.py
  tests/test_merge.py
  tests/test_overviews.py
  tests/test_read_resample.py
  tests/test_rpcs.py
  tests/test_warp.py
  tests/test_warp_transform.py
  tests/test_write.py
Labels: dependencies

#3188 This is 1.4.0
  AUTHORS.txt
  CHANGES.txt
  rasterio/__init__.py
Labels: release

#3189 TST: Check for lowerCase netCDF instead of NetCDF
  tests/test_rio_info.py
  tests/test_subdatasets.py
Labels: bug

#3195 Return ints from dataset index()
  CHANGES.txt
  rasterio/transform.py
Labels: bug

#3197 Add fsspec to test dependencies
  setup.py
Labels: bug
