Repository rasterio/rasterio, pull requests merged in 2024-01, with the labels that each got.

#2991 docs: minor docs changes
  rasterio/features.py
Labels: bug, documentation

#3003 Simplify rasterize
  CHANGES.txt
  rasterio/features.py
  tests/test_features.py
Labels: bug, refactor

#3002 DEP: Use numpy in pyproject.toml
  pyproject.toml
  requirements.txt
  setup.py
Labels: dependencies

#3008 Don't squeeze 2-D arrays when plotting
  CHANGES.txt
  rasterio/plot.py
  tests/test_plot.py
Labels: bug, plotting
