Repository rasterio/rasterio, pull requests merged in 2024-04, with the labels that each got.

#3054 Rel 1.3.10
  .github/workflows/tests.yaml
  CHANGES.txt
  Makefile
  pyproject.toml
  rasterio/__init__.py
  rasterio/_io.pyx
  rasterio/_warp.pyx
  rasterio/rio/main.py
  requirements-dev.txt
  tests/test_cli_main.py
  tests/test_rio_shapes.py
  tests/test_warnings.py
Labels: release

#3056 Don't use approximate transformer with source_geoloc_array
  rasterio/_warp.pyx
  tests/test_warp.py
Labels: bug, cython, warp

#3061 Numpy 2 compatibility
  .github/workflows/tests.yaml
  CHANGES.txt
  Makefile
  pyproject.toml
  rasterio/_io.pyx
  rasterio/_warp.pyx
  rasterio/rio/main.py
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/test_cli_main.py
Labels: cython, numpy

#3063 Remove obsolete tests, update change log
  CHANGES.txt
  tests/test_transform.py
Labels: enhancement

#3046 Better handling for complex values in merge
  rasterio/merge.py
  tests/test_merge.py
Labels: enhancement

#3060 Rel 1.3.10 take 2
  .github/workflows/tests.yaml
  CHANGES.txt
  Makefile
  pyproject.toml
  rasterio/__init__.py
  rasterio/_io.pyx
  rasterio/_warp.pyx
  rasterio/merge.py
  rasterio/rio/main.py
  rasterio/rio/merge.py
  requirements-dev.txt
  setup.py
  tests/test_cli_main.py
  tests/test_rio_shapes.py
  tests/test_warnings.py
Labels: release

#3065 Update change log and version for 1.4a3
  CHANGES.txt
  pyproject.toml
  rasterio/__init__.py
  rasterio/_io.pyx
  rasterio/_vsiopener.pyx
  rasterio/merge.py
  setup.py
  tests/test_merge.py
Labels: release

#3075 Add test for out of range nodata value
  rasterio/merge.py
  tests/test_merge.py
Labels: enhancement, tool

#3076 Fix denominator in max_pixels calculation
  CHANGES.txt
  rasterio/rio/calc.py
Labels: bug
