Repository rasterio/rasterio, pull requests merged in 2024-07, with the labels that each got.

#3109 BUG: Use np.asanyarray in MemoryDataset for numpy 2 compat
  rasterio/_io.pyx
Labels: bug

#3113 Port of Pyopener VSI plugin improvements in Fiona 1.10b2
  CHANGES.txt
  rasterio/_env.pyx
  rasterio/_vsiopener.pxd
  rasterio/_vsiopener.pyx
  rasterio/gdal.pxi
  setup.py
  tests/test_pyopener.py
Labels: bug, enhancement

#3115 Add tests with multiple GDAL threads and implement truncate
  rasterio/_vsiopener.pyx
  tests/test_pyopener.py
  tests/test_warp.py
Labels: bug, enhancement

#3107 update update numpy version
  .github/workflows/tests.yaml
  pyproject.toml
  requirements.txt
Labels: dependencies
